development:
        adapter: mysql2
        encoding: utf8
        reconnect: false
        database: mycampaigns_development
        pool: 5
        username: root
        password: root
        socket: /var/run/mysqld/mysqld.sock


test:
        adapter: mysql2
        encoding: utf8
        reconnect: false
        database: mycampaigns_test
        pool: 5
        username: root
        password: root
        socket: /var/run/mysqld/mysqld.sock

