# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e2ffdb9bf1c913a625ef6c834c885adde36ace302691ab02af2ce1c904dd46253d67aa7356e4a2b3261795ec1117e8d83e22e868f6f5a1e47c3fe84c789d825

test:
  secret_key_base: 33c239d4c41251d8b06f0586185e60c93cc1779708732734ce00b22ea34fd6551688bd2b71f079d96ab4ae024c2d7f2b8bba64c19da0c88c36c980b40bc9649d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 33c239d4c41251d8b06f0586185e60c93cc1779708732734ce00b22ea34fd6551688bd2b71f079d96ab4ae024c2d7f2b8bba64c19da0c88c36c980b40bc964ss
